# Generated by Django 6.0.2 on 2026-03-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_tag', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
