# Generated by Django 5.2.11 on 2026-03-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_gatekeeperflag_ministerflags"),
    ]

    operations = [
        migrations.CreateModel(
            name="KingFlags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flag", models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name="gatekeeperflag",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ministerflags",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="texts",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
